-- ============================================================
--  GPU — INTEGRADA  (solo Intel o solo AMD, sin NVIDIA)
--  Elegido por ~/.config/gigios/gpu-perfil (ver gigios/gpu.lua).
--
--  NO CONFIGURA NADA, Y ESE ES EL PUNTO. Sobre una iGPU sola, Mesa y
--  aquamarine ya eligen bien: la GPU que maneja la pantalla es la única que
--  hay, no existe offload que arbitrar y ninguna de las variables de los
--  perfiles NVIDIA aplica (GBM_BACKEND, __GLX_VENDOR_LIBRARY_NAME y
--  LIBVA_DRIVER_NAME=nvidia sobre Mesa rompen la aceleración de vídeo en vez
--  de mejorarla).
--
--  Este módulo existe para que "no hay nada que configurar" sea una RESPUESTA
--  y no un hueco. Antes la única forma de decirlo era dejar el fichero
--  ausente, y gigios/gpu.lua no distingue "todavía no lo he elegido" de "lo
--  elegí y no hace falta perfil": avisaba en pantalla EN CADA INICIO DE
--  SESIÓN, para siempre, en cualquier portátil AMD o Intel. El instalador
--  escribe este nombre cuando detecta que no hay NVIDIA.
--
--  Si algún día hiciera falta fijar algo específico de esta máquina (un
--  AQ_DRM_DEVICES con varias iGPU, una variable de Mesa), va aquí — pero lee
--  antes las dos trampas de AQ_DRM_DEVICES documentadas en
--  gigios/gpu/sobremesa-nvidia.lua.
-- ============================================================
