-- ============================================================
--  GPU — LAPTOP HÍBRIDA  (Intel Arc Arrow Lake + NVIDIA RTX 5060)
--  Elegido por ~/.config/gigios/gpu-perfil (ver gigios/gpu.lua).
--
--  Modelo: el COMPOSITOR y la PANTALLA corren en Intel (el eDP cuelga
--  de i915). La NVIDIA queda SOLO para offload de juegos/render pesado.
--
--  Para lanzar un juego en la NVIDIA:
--      prime-run <juego>
--      gamemoderun prime-run %command%      (opción de lanzamiento en Steam)
--      gamescope -f -- prime-run %command%
--  prime-run ya inyecta __NV_PRIME_RENDER_OFFLOAD, __GLX_VENDOR_LIBRARY_NAME
--  y __VK_LAYER_NV_optimus por proceso, así que NO hacen falta globales.
-- ============================================================

-- Intel es la GPU primaria (compositor/pantalla); NVIDIA queda para offload.
--
-- NO se fija AQ_DRM_DEVICES a propósito: aquamarine elige como primaria la GPU
-- que maneja la pantalla eDP — la Intel (i915) — automáticamente. Es lo más
-- robusto:
--   - no depende de /dev/dri/cardN (se intercambian entre reinicios),
--   - no depende de rutas by-path (tienen ':' y rompen el parseo),
--   - no puede dejar a Hyprland sin GPU: siempre hay una válida → SIEMPRE arranca.
-- La NVIDIA no tiene pantallas conectadas, así que no se elige como primaria;
-- queda libre para prime-run y puede dormir para ahorrar batería.

-- IMPORTANTE: aquí NO se ponen GBM_BACKEND=nvidia-drm ni
-- __GLX_VENDOR_LIBRARY_NAME=nvidia ni LIBVA_DRIVER_NAME=nvidia globales.
-- El escritorio va en Intel; forzar NVIDIA global mete reverse-PRIME,
-- gasta batería y rompe la aceleración de vídeo (VA-API) de Intel.

-- Con el compositor en Intel los cursores por hardware funcionan bien, y el
-- default `auto` ya resuelve a eso, así que aquí no se fija nada.
--
-- Si alguna vez hiciera falta forzarlo, la clave SÍ acepta el valor (remedido en
-- 0.56.2; la nota anterior decía que lo descartaba y estaba equivocada). Las
-- formas que valen y la que NO, comprobadas con hyprctl eval + getoption:
--
--   hl.config({ cursor = { no_hardware_cursors = false } })  -> int: 0  OK
--   hl.config({ cursor = { no_hardware_cursors = 0 } })      -> int: 0  OK
--   hl.config({ cursor = { no_hardware_cursors = "0" } })    -> sin efecto
--
-- La cadena "0" se descarta EN SILENCIO: `hyprctl eval` responde `ok` y la
-- opción se queda como estaba. Y la forma de clave plana no existe en esta API
-- para ninguna opción: hl.config({ ["cursor:no_hardware_cursors"] = false })
-- da «unknown config key». Usa siempre la tabla anidada con booleano o entero.
